# https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.14/#replicaset-v1-apps
---
apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name:
spec:
  replicas:
  selector:
    matchLabels:
  template:
    # pod template