# https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.14/#service-v1-core
---
apiVersion: v1
kind: Service
metadata:
  name:
spec:
  ports:
  - name:
    port:
    protocol:
    targetPort:
    nodePort:
  selector:
  type:
