# https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.14/#persistentvolumeclaim-v1-core
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name:
spec:
  accessModes:
  resources:
    requests:
      storage:
