# https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.14/#cronjob-v1beta1-batch
---
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name:
spec:
  schedule:
  successfulJobsHistoryLimit:
  failedJobsHistoryLimit:
  jobTemplate:
    # job template
